with open("app.py", "r", encoding="utf-8") as f:
    lines = f.readlines()

new_func = [
    'def _is_tag_query(prompt: str) -> str:\n',
    '    p = prompt.lower()\n',
    '    no_tags = ["sin tag", "sin etiqueta", "no tiene tag", "no tienen tag",\n',
    '               "sin tags", "sin etiquetas", "recursos sin", "without tag",\n',
    '               "no tienen etiqueta", "recursos que no tienen"]\n',
    '    has_tags = ["tags del recurso", "etiquetas del recurso", "que tags tiene",\n',
    '                "ver tags", "mostrar tags", "tags asignados a", "que etiquetas tiene"]\n',
    '    if any(k in p for k in no_tags):\n',
    '        return "without"\n',
    '    if any(k in p for k in has_tags):\n',
    '        return "get"\n',
    '    return ""\n',
    '\n',
    '\n',
    'def _format_tags_response(result_json: str, query_type: str) -> str:\n',
    '    import json as _json\n',
    '    try:\n',
    '        data = _json.loads(result_json)\n',
    '        if "error" in data:\n',
    '            return f"Error al consultar Azure: {data[chr(39)+chr(101)+chr(114)+chr(114)+chr(111)+chr(114)+chr(39)]}"\n',
    '        if query_type == "without":\n',
    '            total = data.get("total_without_tags", 0)\n',
    '            resources = data.get("resources", [])\n',
    '            if total == 0:\n',
    '                return "Todos los recursos en Azure tienen tags asignados."\n',
    '            out = [f"Se encontraron **{total} recursos sin tags** en Azure:\\n"]\n',
    '            for r in resources[:20]:\n',
    '                cols = data.get("columns", [])\n',
    '                if isinstance(r, dict):\n',
    '                    out.append(f"- **{r.get(\'name\',\'?\')}** | {r.get(\'type\',\'?\')} | RG: {r.get(\'resourceGroup\',\'?\')}")\n',
    '                elif isinstance(r, list) and len(r) >= 4:\n',
    '                    out.append(f"- **{r[1]}** | {r[2]} | RG: {r[3]}")\n',
    '            if total > 20:\n',
    '                out.append(f"\\n...y {total-20} recursos mas.")\n',
    '            out.append("\\n**Recomendacion FinOps:** Asigna businessOwner y env a cada recurso sin tags.")\n',
    '            return "\\n".join(out)\n',
    '        if query_type == "get":\n',
    '            tags = data.get("tags", {})\n',
    '            if not data.get("has_tags", False):\n',
    '                return "El recurso **no tiene tags asignados**. Asigna: businessOwner, env, businessUnit, ac."\n',
    '            out = [f"**{data.get(\'tags_count\',0)} tags encontrados:**\\n"]\n',
    '            for k, v in tags.items():\n',
    '                out.append(f"- **{k}**: {v}")\n',
    '            return "\\n".join(out)\n',
    '    except Exception as e:\n',
    '        return f"Error: {e}"\n',
    '\n',
    '\n',
    'def ask_with_fallback(prompt: str):\n',
    '    tag_mode = _is_tag_query(prompt)\n',
    '    if tag_mode == "without":\n',
    '        result = get_azure_resources_without_tags()\n',
    '        return _format_tags_response(result, "without"), "azure-resource-graph"\n',
    '    if tag_mode == "get":\n',
    '        result = get_azure_resource_tags(prompt)\n',
    '        return _format_tags_response(result, "get"), "azure-resource-graph"\n',
    '\n',
    '    last_error = None\n',
    '    for model_name in MODEL_NAMES:\n',
    '        try:\n',
    '            model = genai.GenerativeModel(\n',
    '                model_name=model_name,\n',
    '                tools=TOOLS,\n',
    '                system_instruction=SYSTEM_INSTRUCTION,\n',
    '            )\n',
    '            chat = model.start_chat(enable_automatic_function_calling=True)\n',
    '            response = chat.send_message(prompt)\n',
    '            return response.text, model_name\n',
    '        except ResourceExhausted as e:\n',
    '            last_error = e\n',
    '            st.info(f"Cuota agotada en model. Intentando con el siguiente...")\n',
    '            continue\n',
    '    raise last_error\n',
    '\n',
]

lines[515:541] = new_func

with open("app.py", "w", encoding="utf-8") as f:
    f.writelines(lines)

print("OK: bypass insertado en lineas 515-540")
